version: "1.0"

services:
  webapp1:
    image: dariuszdulko/webapp:1.0
    networks:
      - test-network
    ports:
      - "8081:80"
  webapp2:
    image: dariuszdulko/webapp:1.0
    networks:
      - test-network
    ports:
      - "8082:80"
  webapp3:
    image: dariuszdulko/webapp:1.0
    networks:
      - test-network 
    ports:
      - "8083:80"
  haproxy:
    image: dariuszdulko/haproxy:1.0
    networks:
      - test-network 
    ports:
      - "8084:8084"

networks:
  external: 
  test-network:
    name: test-network
    driver: bridge