FROM httpd:2.4-alpine

LABEL app="test-webapp"

RUN apk update && \
    apk add vim

CMD ["/bin/sh", "-c", "echo '<html><head><title>Dariusz Dulko</title></head><body><h1>Welcome to this fabulous test page under hostname: <font color='green'>'$(hostname)'</font><br> You can even imagine looking at beautiful logo and login page!</h1></body></html' > /usr/local/apache2/htdocs/index.html; httpd -D FOREGROUND"]